# Generated by Django 2.2.12 on 2021-06-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_book_genres',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('history', 'History'), ('memoir', 'Memoir'), ('politics', 'Politics'), ('science Fiction', 'Science Fiction')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_movie_genres',
            field=models.CharField(blank=True, choices=[('action', 'Action'), ('romance', 'Romance'), ('mistery', 'Mistery'), ('horror', 'Horror'), ('comedy', 'Comedy')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('kr', 'Korean')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preference',
            field=models.CharField(blank=True, choices=[('books', 'Books'), ('movies', 'Movies')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='superhost',
            field=models.BooleanField(default=False),
        ),
    ]
