# Generated by Django 2.2.12 on 2021-06-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210601_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite_book_genres',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('history', 'History'), ('memoir', 'Memoir'), ('politics', 'Politics'), ('science Fiction', 'Science Fiction')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='favourite_movie_genres',
            field=models.CharField(blank=True, choices=[('action', 'Action'), ('romance', 'Romance'), ('mistery', 'Mistery'), ('horror', 'Horror'), ('comedy', 'Comedy')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.CharField(blank=True, choices=[('books', 'Books'), ('movies', 'Movies')], max_length=20, null=True),
        ),
    ]
